services:
  #BACKEND SERVICE 
  api:
    build: backend
    ports:
      - "8080:8080"
    
    depends_on:
      - db
    #take content of env file in the backend directory
    env_file:
      - ./backend/.env

  
  #DATABASE SERVICE
  db:
    image: postgres:17-alpine
    env_file:
      - ./backend/.env 


  #FRONTEND SERVICE
  web:
    build: frontend
    ports:
      - "8081:80"
    env_file:
      - ./frontend/.env